# Generated by Django 2.2.5 on 2020-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='songs', to='single_view.Source', verbose_name='Sources'),
        ),
    ]
