# Generated by Django 2.2.5 on 2020-09-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_view', '0002_song_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='sources',
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='single_view.Source', verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
